### ISSUE TITLE
metadata.json is missing EULASlug

### ISSUE THREAD

**Issue by mmb** [pivotal-cf-experimental/pivnet-resource#25]
The metadata.json file has an empty string for EULASlug for OpsMan 1.7.0.0

```
{
  "Release": {
    "Version": "1.7.0.0",
    "ReleaseType": "Minor Release",
    "EULASlug": "",
```

This product has a EULA on Pivotal Network.

Using latest-final tag of pivnet-resource.

**Comment by robdimsdale** [comment]
Thanks for this, looks like a bug when we extracted the [go-pivnet library](http://github.com/pivotal-cf-experimental/go-pivnet). We will fix this and #26 ASAP

**Comment by robdimsdale** [comment]
Just an update on this - we are in the process of refactoring to merge the [go-pivnet library](https://github.com/pivotal-cf-experimental/go-pivnet) into the pivnet resource - this may fix the bug, but even if not we want to move forward on a more stable foundation.

**Comment by robdimsdale** [comment]
@mmb FYI this is now fixed and will be available in the next final release. Thanks for your patience on this.

**Comment by robdimsdale** [comment]
(and that new final release is now available)
