### ISSUE TITLE
metadata.json is missing MD5

### ISSUE THREAD

**Issue by mmb** [pivotal-cf-experimental/pivnet-resource#26]
The metadata.json file has an empty string for MD5 for OpsMan 1.7.0.0

```
  "ProductFiles": [
    {
      "File": "Pivotal Cloud Foundry Ops Manager for AWS - 1.7.0.0",
      "Description": "",
      "UploadAs": "",
      "AWSObjectKey": "product_files/Pivotal-CF/OpsManager1.7.0.0onAWS.pdf",
      "FileType": "",
      "FileVersion": "1.7.0.0",
      "MD5": "",
```

This product has an MD5 on Pivotal Network.

Using latest-final tag of pivnet-resource.

**Comment by robdimsdale** [comment]
Thanks for this, looks like a bug when we extracted the [go-pivnet library](http://github.com/pivotal-cf-experimental/go-pivnet). We will fix this and #25 ASAP

**Comment by robdimsdale** [comment]
Just an update on this - we are in the process of refactoring to merge the [go-pivnet library](https://github.com/pivotal-cf-experimental/go-pivnet) into the pivnet resource - this may fix the bug, but even if not we want to move forward on a more stable foundation.

**Comment by robdimsdale** [comment]
@mmb FYI this is now fixed and will be available in the next final release. Thanks for your patience on this.

**Comment by robdimsdale** [comment]
(and that new final release is now available)
