### ISSUE TITLE
Support 'version_type' to allow triggers on 'major' or 'minor' version number

### ISSUE THREAD

**Issue by xtremerui** [pivotal-cf-experimental/pivnet-resource#27]
Hi, we have a problem with Pivnet Resource updates when new stemcell is released. In our pipeline, we want it to trigger only if the new released stemcell has higher major version than our current one. Right now, we have a task there to take both version numbers as inputs and compare them in the task container. The container will return true or false, so our pipeline knows if it should proceed or not. It is working but the issue is that it will make the job RED if false, which makes our pipeline look bad. 

For example, pivnet resource is triggered now for 3146.12 since it is the latest release (timeline wise) in pivnet. But in our pipeline we already have the latest version 3232.4 (version wise). We don't want it to update in this case.

For our case we would like to have something like:
`  - name: pivnet-stemcells
     type: pivnet
     source:
       api_token: _sample_token_
       product_slug: stemcells
       version_type: major` 

version_type: minor | major

**Comment by robdimsdale** [comment]
Sounds good. There's already a story for this: [117119027](https://www.pivotaltracker.com/story/show/117119027) with a proposed version of `minor|major` just like you suggest.

As noted in the story, I think it would be cleaner to support a version regex, with semantic versioning support, similar to how some of the other concourse resources (e.g. the s3 resource) behave.

If we went down the regex route I would imagine seeing something like:

```
source:
  api_token: _sample_token_
  product_slug: stemcells
  version: (.*)
```

And the versions that came back would be ordered sematically, meaning your use-case would be solved.

However, I think that `version_type` is quite a bit easier to implement, so we might prefer to do that first.

**Comment by davewalter** [comment]
+1!

The version regex option would also solve a problem that PCF Release Engineering have recently encountered where we would like to pin to a particular major/minor version and just float on the patch level of the release.

**Comment by robdimsdale** [comment]
Thinking about this some more, my first suggestion of `version_type: major|minor` and the story I originally linked to is not relevant here; I was thinking of `release_type` but in the example given of stemcells, both of the stemcells are `Security Release` so we can only differentiate them from the version numbers.

So, the only way to solve this is by parsing the version number and ordering semantically.

@davewalter your requirement is a subset of the one @xtremerui wants - you both want to filter on versions but you don't care about semantic ordering (and @xtremerui doesn't care about pinning to major/minor versions).

There's a story to tackle the first part (filtering on regex):

- [pivnet resource check should filter on version via regex in source config](https://www.pivotaltracker.com/story/show/123679481)

and then there's a placeholder story to tackle the extension of this to return the versions ordered semantically:

- [PLACEHOLDER: allow (force?) some sort of (semver?) regex for check / in / out](https://www.pivotaltracker.com/story/show/108244220)

We can more easily scope the second story (semver ordering) once we've implemented the first.

Sound good?

Thanks,
Rob

**Comment by davewalter** [comment]
Sounds good. We only care about semantic ordering in so far as we want the highest version that matches the specified regex. Given that we are extremely unlikely to release a lower patch number of a specific major/minor release after a higher one, the order should take care of itself.

Thanks,
Dave

**Comment by robdimsdale** [comment]
That's what I was expecting your workflow looked like - thanks for clarifying. I'll close this issue now, as the necessary stories have been created and prioritized.
