### ISSUE TITLE
Consuming lots of disk space

### ISSUE THREAD

**Issue by cgfrost** [pivotal-cf-experimental/pivnet-resource#33]
We're seeing a problem with our pipeline running out of disk space and the only recent change is to start using pivnet-resource. How does it control cache usage and deletion of old versions etc... This may not be a bug with pivnet-resource but at this point I can't prove it isn't and I have no other suspects.

**Comment by robdimsdale** [comment]
You might be running into an issue we just fixed - leaking logs on the check container. The newest release (released yesterday) fixes this, but I don't know how best to bounce all of your check containers. I would ask @vito if there's a good way to do this.

**Comment by vito** [comment]
The check containers should stop being used after ~1 hour. Are the logs that verbose?

**Comment by robdimsdale** [comment]
The `check` logs files are about 400KB. If we generate a new one per minute (default check interval) then we can assume 24MB per hour, per resource. Maybe if there's a lot of resources, and the disk size is relatively small this could be a problem?

**Comment by robdimsdale** [comment]
And when you say "stop being used" are you saying in the steady-state case the check containers are recycled after one hour, or are you saying that if one pauses/deletes a pipeline it takes one hour to delete them?

**Comment by cgfrost** [comment]
It seems most of our disk is consumed with baggage claim in garden. 24GB of it, I don't think we've accumulated 1000 hours of logs just yet.

**Comment by zachgersh** [comment]
@cgfrost what version of concourse are you on?

**Comment by cgfrost** [comment]
Version 1.4.1. 
It's worth mentioning we're using the `pivnet-resource` a lot, we have 10 of them defined.

**Comment by robdimsdale** [comment]
@vito does the latest check container get pulled after that 1 hour you describe? I.e. will the rogue rootfs go away over time, or will concourse create more containers with the bad rootfs?

Also, @cgfrost, based on the numbers you describe, I don't think the issue is logs. Even with 10 resources, we're about two orders of magnitude off the usage you report. Are you downloading lots of large files like elastic runtime?

**Comment by zachgersh** [comment]
@cgfrost also worth asking whether you have lots of failed builds with containers sitting around that have large assets in them.

**Comment by cgfrost** [comment]
Yeah, two versions of elastic runtime, two versions of OpsManager, two versions of Mysql, two versions of Rabbit and two different stemcells.

**Comment by cgfrost** [comment]
A failed build will leave the container laying around, that sounds like a possibility. When a build fails do you know if it will then clean away previous failed build.

**Comment by cgfrost** [comment]
Am I right in saying that all downloads live inside the job containers? Is nothing cached elsewhere?

**Comment by zachgersh** [comment]
@cgfrost it only keeps the latest failed build for that job (if you have successive failures). I think What @robdimsdale pointed out is most likely the problem - lots of assets being downloaded. How big are the discs you have elsewhere?

**Comment by cgfrost** [comment]
hmmm 3TB for all the concourse vms apparently but the usage I'm seeing from one of the workers that I ssh ed in to is different. 
``` bash
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G  4.0K  3.9G   1% /dev
tmpfs           799M  888K  798M   1% /run
/dev/sda1       2.9G  1.4G  1.4G  49% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            3.9G     0  3.9G   0% /run/shm
none            100M     0  100M   0% /run/user
/dev/sdb2        24G   24G     0 100% /var/vcap/data
tmpfs           1.0M   20K 1004K   2% /var/vcap/data/sys/run
/dev/loop0      120M  1.6M  115M   2% /tmp
/dev/loop1       24G   20G  2.9G  87% /var/vcap/data/baggageclaim/volumes
```

**Comment by cgfrost** [comment]
A ruff sum of all the files I'm downloading comes to about 17GB.

**Comment by vito** [comment]
if you run `fly volumes` it'll show the size and type of each volume.

@robdimsdale concourse will stop reusing a check container after an hour,
leaving it to expire which may take ~5 mins

**Comment by cgfrost** [comment]
That gives me a very long list of volumes, I can see a few taking up a few gig each. I also have a lot of active containers `fly containers`

**Comment by cgfrost** [comment]
I'm going to try upping the disk space from bosh, will report back here either way.

**Comment by vito** [comment]
Yeah you may want to just eyeball `fly volumes`, and if nothing jumps out, I'd assume you just need more disk. That output should account for 100% of the disk usage, including ephemeral stuff like the copy-on-write layers for in-flight builds.

24G is not a lot, for how large PivNet artifacts tend to be. If you've given them 3TB of persistent disk that won't work - all this data is on the ephemeral disk.

**Comment by cgfrost** [comment]
Things are looking a lot better with more disk space, will have to wait over time to see if it runs out again. I've book marked this thread so I have a better idea of what to check in future. Thanks for the pointers all.

**Comment by robdimsdale** [comment]
Glad to hear it, thanks for the update
